# Static
env: "mujoco_multi"
name: "masaj"
runner: "masaj" # "masaj_parallel"
# batch_size_run: 2 # Number of environments to run in parallel
mac: "role_mac"
learner: "masaj_learner"
agent: "rode" # TODO: malaya
role_selector: "multinomial_role"
role: "msj"

# Ambient dependent
continuous_actions: True
action_selector: "gaussian_latent"
use_latent_normal: True

# Encoder-decoder for actions
action_encoder: "obs_reward"

# Epsilon scheduler and masking
epsilon_start: 1.0
epsilon_finish: .05
epsilon_anneal_time: 70000
epsilon_anneal_time_exp: 70000
mask_before_softmax: True

# Learners hyperparameters
batch_size: 32
target_update_interval: 200
lr: 0.0005
c_lr: 0.0005
v_lr: 0.0005
td_lambda: 0.8
role_interval: 5
role_action_spaces_update_start: 50000
use_role_value: False

# Network structure hyper-parameters
obs_role: True # Pass roles as observations to critics
n_roles: 3
n_role_clusters: 5
state_latent_dim: 32
action_latent_dim: 20
mixing_embed_dim: 32
n_head: 4  

# Buffer hyper-parameters
buffer_size: 5000
burn_in_period: 100

# Logging parameters
log_interval: 5000 # Log summary of stats after every {} timesteps
runner_log_interval: 5000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 5000 # Log training stats every {} timesteps
